server {
    listen 85;
    server_name localhost;
 
    # Root directory for the Vue.js app
    root /usr/share/nginx/html;
    index index.html;
 
    # Serve static files
    location / {
        try_files $uri $uri/ /index.html;
    }
 
    # Handle requests for assets like JavaScript, CSS, images, etc.
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
